/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.zenika.avro.price;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Price extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Price\",\"namespace\":\"com.zenika.avro.price\",\"fields\":[{\"name\":\"price\",\"type\":\"double\",\"doc\":\"The price\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The price */
  @Deprecated public double price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Price() {}

  /**
   * All-args constructor.
   */
  public Price(java.lang.Double price) {
    this.price = price;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return price;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: price = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'price' field.
   * The price   */
  public java.lang.Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * The price   * @param value the value to set.
   */
  public void setPrice(java.lang.Double value) {
    this.price = value;
  }

  /** Creates a new Price RecordBuilder */
  public static com.zenika.avro.price.Price.Builder newBuilder() {
    return new com.zenika.avro.price.Price.Builder();
  }
  
  /** Creates a new Price RecordBuilder by copying an existing Builder */
  public static com.zenika.avro.price.Price.Builder newBuilder(com.zenika.avro.price.Price.Builder other) {
    return new com.zenika.avro.price.Price.Builder(other);
  }
  
  /** Creates a new Price RecordBuilder by copying an existing Price instance */
  public static com.zenika.avro.price.Price.Builder newBuilder(com.zenika.avro.price.Price other) {
    return new com.zenika.avro.price.Price.Builder(other);
  }
  
  /**
   * RecordBuilder for Price instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Price>
    implements org.apache.avro.data.RecordBuilder<Price> {

    private double price;

    /** Creates a new Builder */
    private Builder() {
      super(com.zenika.avro.price.Price.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.zenika.avro.price.Price.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.price)) {
        this.price = data().deepCopy(fields()[0].schema(), other.price);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Price instance */
    private Builder(com.zenika.avro.price.Price other) {
            super(com.zenika.avro.price.Price.SCHEMA$);
      if (isValidValue(fields()[0], other.price)) {
        this.price = data().deepCopy(fields()[0].schema(), other.price);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'price' field */
    public java.lang.Double getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public com.zenika.avro.price.Price.Builder setPrice(double value) {
      validate(fields()[0], value);
      this.price = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'price' field */
    public com.zenika.avro.price.Price.Builder clearPrice() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public Price build() {
      try {
        Price record = new Price();
        record.price = fieldSetFlags()[0] ? this.price : (java.lang.Double) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
